// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/fvc.proto

// Le package correspond maintenant au nom de ton projet : fvc

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Messages pour la commande RUN ---
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // Le chemin du Vmfile ou le nom de l'image
	Config        *VmConfig              `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_fvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RunRequest) GetConfig() *VmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                         // L'identifiant unique généré (ex: vm-fvc-999)
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // Statut initial
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Message d'erreur si échec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_fvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	VmId          string                 `protobuf:"bytes,4,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_proto_fvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{2}
}

func (x *RunEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RunEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunEvent) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RunEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// --- Messages pour la commande STOP ---
type StopRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VmId           string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_fvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_fvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{4}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_fvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{5}
}

func (x *StartRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_fvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{6}
}

func (x *StartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmRequest) Reset() {
	*x = RmRequest{}
	mi := &file_proto_fvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmRequest) ProtoMessage() {}

func (x *RmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmRequest.ProtoReflect.Descriptor instead.
func (*RmRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{7}
}

func (x *RmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type RmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmResponse) Reset() {
	*x = RmResponse{}
	mi := &file_proto_fvc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmResponse) ProtoMessage() {}

func (x *RmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmResponse.ProtoReflect.Descriptor instead.
func (*RmResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{8}
}

func (x *RmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsoleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInfoRequest) Reset() {
	*x = ConsoleInfoRequest{}
	mi := &file_proto_fvc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInfoRequest) ProtoMessage() {}

func (x *ConsoleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInfoRequest.ProtoReflect.Descriptor instead.
func (*ConsoleInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{9}
}

func (x *ConsoleInfoRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type ConsoleInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VmId          string                 `protobuf:"bytes,3,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	LogPath       string                 `protobuf:"bytes,4,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	InputPath     string                 `protobuf:"bytes,5,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInfoResponse) Reset() {
	*x = ConsoleInfoResponse{}
	mi := &file_proto_fvc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInfoResponse) ProtoMessage() {}

func (x *ConsoleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInfoResponse.ProtoReflect.Descriptor instead.
func (*ConsoleInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{10}
}

func (x *ConsoleInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsoleInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConsoleInfoResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleInfoResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *ConsoleInfoResponse) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

// --- Messages pour la commande PS ---
type PsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsRequest) Reset() {
	*x = PsRequest{}
	mi := &file_proto_fvc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsRequest) ProtoMessage() {}

func (x *PsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsRequest.ProtoReflect.Descriptor instead.
func (*PsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{11}
}

func (x *PsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type VmConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          int32                  `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Ports         []string               `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmConfig) Reset() {
	*x = VmConfig{}
	mi := &file_proto_fvc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmConfig) ProtoMessage() {}

func (x *VmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmConfig.ProtoReflect.Descriptor instead.
func (*VmConfig) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{12}
}

func (x *VmConfig) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *VmConfig) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VmConfig) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type VmDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Config        *VmConfig              `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	GuestIp       string                 `protobuf:"bytes,7,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	MacAddress    string                 `protobuf:"bytes,8,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	TapName       string                 `protobuf:"bytes,9,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmDetails) Reset() {
	*x = VmDetails{}
	mi := &file_proto_fvc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDetails) ProtoMessage() {}

func (x *VmDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDetails.ProtoReflect.Descriptor instead.
func (*VmDetails) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{13}
}

func (x *VmDetails) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VmDetails) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VmDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VmDetails) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VmDetails) GetConfig() *VmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *VmDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VmDetails) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *VmDetails) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *VmDetails) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

type PsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VmDetails           `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"` // La liste de toutes les microVMs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsResponse) Reset() {
	*x = PsResponse{}
	mi := &file_proto_fvc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsResponse) ProtoMessage() {}

func (x *PsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsResponse.ProtoReflect.Descriptor instead.
func (*PsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{14}
}

func (x *PsResponse) GetVms() []*VmDetails {
	if x != nil {
		return x.Vms
	}
	return nil
}

// --- Messages pour la commande LOGS ---
type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int32                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_fvc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{15}
}

func (x *LogsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_fvc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fvc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fvc_proto_rawDescGZIP(), []int{16}
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_fvc_proto protoreflect.FileDescriptor

const file_proto_fvc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/fvc.proto\x12\x03fvc\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\n" +
	"RunRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12%\n" +
	"\x06config\x18\x02 \x01(\v2\r.fvc.VmConfigR\x06config\"_\n" +
	"\vRunResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8c\x01\n" +
	"\bRunEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x13\n" +
	"\x05vm_id\x18\x04 \x01(\tR\x04vmId\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"K\n" +
	"\vStopRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\fStartRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"C\n" +
	"\rStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\tRmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"@\n" +
	"\n" +
	"RmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x12ConsoleInfoRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x98\x01\n" +
	"\x13ConsoleInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x13\n" +
	"\x05vm_id\x18\x03 \x01(\tR\x04vmId\x12\x19\n" +
	"\blog_path\x18\x04 \x01(\tR\alogPath\x12\x1d\n" +
	"\n" +
	"input_path\x18\x05 \x01(\tR\tinputPath\"\x1d\n" +
	"\tPsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"Q\n" +
	"\bVmConfig\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x05R\x04cpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x14\n" +
	"\x05ports\x18\x03 \x03(\tR\x05ports\"\x99\x02\n" +
	"\tVmDetails\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12%\n" +
	"\x06config\x18\x05 \x01(\v2\r.fvc.VmConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bguest_ip\x18\a \x01(\tR\aguestIp\x12\x1f\n" +
	"\vmac_address\x18\b \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\btap_name\x18\t \x01(\tR\atapName\".\n" +
	"\n" +
	"PsResponse\x12 \n" +
	"\x03vms\x18\x01 \x03(\v2\x0e.fvc.VmDetailsR\x03vms\"N\n" +
	"\vLogsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x05R\x04tail\"\\\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x87\x03\n" +
	"\n" +
	"FvcService\x12(\n" +
	"\x03Run\x12\x0f.fvc.RunRequest\x1a\x10.fvc.RunResponse\x12-\n" +
	"\tRunStream\x12\x0f.fvc.RunRequest\x1a\r.fvc.RunEvent0\x01\x12+\n" +
	"\x04Stop\x12\x10.fvc.StopRequest\x1a\x11.fvc.StopResponse\x12.\n" +
	"\x05Start\x12\x11.fvc.StartRequest\x1a\x12.fvc.StartResponse\x12%\n" +
	"\x02Rm\x12\x0e.fvc.RmRequest\x1a\x0f.fvc.RmResponse\x12@\n" +
	"\vConsoleInfo\x12\x17.fvc.ConsoleInfoRequest\x1a\x18.fvc.ConsoleInfoResponse\x12%\n" +
	"\x02Ps\x12\x0e.fvc.PsRequest\x1a\x0f.fvc.PsResponse\x123\n" +
	"\n" +
	"StreamLogs\x12\x10.fvc.LogsRequest\x1a\x11.fvc.LogsResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_fvc_proto_rawDescOnce sync.Once
	file_proto_fvc_proto_rawDescData []byte
)

func file_proto_fvc_proto_rawDescGZIP() []byte {
	file_proto_fvc_proto_rawDescOnce.Do(func() {
		file_proto_fvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fvc_proto_rawDesc), len(file_proto_fvc_proto_rawDesc)))
	})
	return file_proto_fvc_proto_rawDescData
}

var file_proto_fvc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_fvc_proto_goTypes = []any{
	(*RunRequest)(nil),            // 0: fvc.RunRequest
	(*RunResponse)(nil),           // 1: fvc.RunResponse
	(*RunEvent)(nil),              // 2: fvc.RunEvent
	(*StopRequest)(nil),           // 3: fvc.StopRequest
	(*StopResponse)(nil),          // 4: fvc.StopResponse
	(*StartRequest)(nil),          // 5: fvc.StartRequest
	(*StartResponse)(nil),         // 6: fvc.StartResponse
	(*RmRequest)(nil),             // 7: fvc.RmRequest
	(*RmResponse)(nil),            // 8: fvc.RmResponse
	(*ConsoleInfoRequest)(nil),    // 9: fvc.ConsoleInfoRequest
	(*ConsoleInfoResponse)(nil),   // 10: fvc.ConsoleInfoResponse
	(*PsRequest)(nil),             // 11: fvc.PsRequest
	(*VmConfig)(nil),              // 12: fvc.VmConfig
	(*VmDetails)(nil),             // 13: fvc.VmDetails
	(*PsResponse)(nil),            // 14: fvc.PsResponse
	(*LogsRequest)(nil),           // 15: fvc.LogsRequest
	(*LogsResponse)(nil),          // 16: fvc.LogsResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_proto_fvc_proto_depIdxs = []int32{
	12, // 0: fvc.RunRequest.config:type_name -> fvc.VmConfig
	12, // 1: fvc.VmDetails.config:type_name -> fvc.VmConfig
	17, // 2: fvc.VmDetails.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: fvc.PsResponse.vms:type_name -> fvc.VmDetails
	17, // 4: fvc.LogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: fvc.FvcService.Run:input_type -> fvc.RunRequest
	0,  // 6: fvc.FvcService.RunStream:input_type -> fvc.RunRequest
	3,  // 7: fvc.FvcService.Stop:input_type -> fvc.StopRequest
	5,  // 8: fvc.FvcService.Start:input_type -> fvc.StartRequest
	7,  // 9: fvc.FvcService.Rm:input_type -> fvc.RmRequest
	9,  // 10: fvc.FvcService.ConsoleInfo:input_type -> fvc.ConsoleInfoRequest
	11, // 11: fvc.FvcService.Ps:input_type -> fvc.PsRequest
	15, // 12: fvc.FvcService.StreamLogs:input_type -> fvc.LogsRequest
	1,  // 13: fvc.FvcService.Run:output_type -> fvc.RunResponse
	2,  // 14: fvc.FvcService.RunStream:output_type -> fvc.RunEvent
	4,  // 15: fvc.FvcService.Stop:output_type -> fvc.StopResponse
	6,  // 16: fvc.FvcService.Start:output_type -> fvc.StartResponse
	8,  // 17: fvc.FvcService.Rm:output_type -> fvc.RmResponse
	10, // 18: fvc.FvcService.ConsoleInfo:output_type -> fvc.ConsoleInfoResponse
	14, // 19: fvc.FvcService.Ps:output_type -> fvc.PsResponse
	16, // 20: fvc.FvcService.StreamLogs:output_type -> fvc.LogsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_fvc_proto_init() }
func file_proto_fvc_proto_init() {
	if File_proto_fvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fvc_proto_rawDesc), len(file_proto_fvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fvc_proto_goTypes,
		DependencyIndexes: file_proto_fvc_proto_depIdxs,
		MessageInfos:      file_proto_fvc_proto_msgTypes,
	}.Build()
	File_proto_fvc_proto = out.File
	file_proto_fvc_proto_goTypes = nil
	file_proto_fvc_proto_depIdxs = nil
}
