// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/fvc.proto

// Le package correspond maintenant au nom de ton projet : fvc

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FvcService_Run_FullMethodName              = "/fvc.FvcService/Run"
	FvcService_RunStream_FullMethodName        = "/fvc.FvcService/RunStream"
	FvcService_Stop_FullMethodName             = "/fvc.FvcService/Stop"
	FvcService_Start_FullMethodName            = "/fvc.FvcService/Start"
	FvcService_Rm_FullMethodName               = "/fvc.FvcService/Rm"
	FvcService_ConsoleInfo_FullMethodName      = "/fvc.FvcService/ConsoleInfo"
	FvcService_Exec_FullMethodName             = "/fvc.FvcService/Exec"
	FvcService_Inspect_FullMethodName          = "/fvc.FvcService/Inspect"
	FvcService_PullImage_FullMethodName        = "/fvc.FvcService/PullImage"
	FvcService_PullImageStream_FullMethodName  = "/fvc.FvcService/PullImageStream"
	FvcService_ListImages_FullMethodName       = "/fvc.FvcService/ListImages"
	FvcService_Prune_FullMethodName            = "/fvc.FvcService/Prune"
	FvcService_Stats_FullMethodName            = "/fvc.FvcService/Stats"
	FvcService_Wait_FullMethodName             = "/fvc.FvcService/Wait"
	FvcService_Kill_FullMethodName             = "/fvc.FvcService/Kill"
	FvcService_SnapshotCreate_FullMethodName   = "/fvc.FvcService/SnapshotCreate"
	FvcService_SnapshotList_FullMethodName     = "/fvc.FvcService/SnapshotList"
	FvcService_SnapshotRestore_FullMethodName  = "/fvc.FvcService/SnapshotRestore"
	FvcService_SnapshotRemove_FullMethodName   = "/fvc.FvcService/SnapshotRemove"
	FvcService_BuildImage_FullMethodName       = "/fvc.FvcService/BuildImage"
	FvcService_BuildImageStream_FullMethodName = "/fvc.FvcService/BuildImageStream"
	FvcService_ImageInspect_FullMethodName     = "/fvc.FvcService/ImageInspect"
	FvcService_ImageRemove_FullMethodName      = "/fvc.FvcService/ImageRemove"
	FvcService_ImageTag_FullMethodName         = "/fvc.FvcService/ImageTag"
	FvcService_ImageImport_FullMethodName      = "/fvc.FvcService/ImageImport"
	FvcService_ImageExport_FullMethodName      = "/fvc.FvcService/ImageExport"
	FvcService_ImageHistory_FullMethodName     = "/fvc.FvcService/ImageHistory"
	FvcService_ImagePrune_FullMethodName       = "/fvc.FvcService/ImagePrune"
	FvcService_Ps_FullMethodName               = "/fvc.FvcService/Ps"
	FvcService_StreamLogs_FullMethodName       = "/fvc.FvcService/StreamLogs"
	FvcService_Diagnostics_FullMethodName      = "/fvc.FvcService/Diagnostics"
)

// FvcServiceClient is the client API for FvcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Le service est renommé FvcService (consommé par fvc, implémenter par fvcd)
type FvcServiceClient interface {
	// Phase 1 & 5 : Lance une microVM
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Lance une microVM en streamant les étapes de préparation
	RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	// Phase 5 : Arrête proprement une microVM
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Relance une microVM stoppée
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Supprime une microVM stoppée et ses fichiers locaux
	Rm(ctx context.Context, in *RmRequest, opts ...grpc.CallOption) (*RmResponse, error)
	// Retourne les chemins locaux nécessaires à la console série
	ConsoleInfo(ctx context.Context, in *ConsoleInfoRequest, opts ...grpc.CallOption) (*ConsoleInfoResponse, error)
	// Exécute une commande dans une microVM via l'agent invité
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecEvent], error)
	// Retourne les détails complets d'une microVM
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	// Télécharge une image dans le cache local
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	// Télécharge une image en streamant la progression
	PullImageStream(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error)
	// Liste les images présentes dans le cache local
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Nettoie les ressources locales inutilisées
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error)
	// Retourne les métriques host des microVMs
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Attend qu'une microVM atteigne l'état stopped/down
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	// Force l'arrêt d'une microVM
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	// Crée un snapshot du disque d'une microVM stoppée
	SnapshotCreate(ctx context.Context, in *SnapshotCreateRequest, opts ...grpc.CallOption) (*SnapshotCreateResponse, error)
	// Liste les snapshots d'une microVM
	SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	// Restaure un snapshot sur le disque d'une microVM stoppée
	SnapshotRestore(ctx context.Context, in *SnapshotRestoreRequest, opts ...grpc.CallOption) (*SnapshotRestoreResponse, error)
	// Supprime un snapshot
	SnapshotRemove(ctx context.Context, in *SnapshotRemoveRequest, opts ...grpc.CallOption) (*SnapshotRemoveResponse, error)
	// Construit une image locale depuis un Fvcfile TOML
	BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*BuildImageResponse, error)
	// Construit une image locale en streamant les étapes
	BuildImageStream(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error)
	// Inspecte une image locale
	ImageInspect(ctx context.Context, in *ImageInspectRequest, opts ...grpc.CallOption) (*ImageInspectResponse, error)
	// Supprime une image locale
	ImageRemove(ctx context.Context, in *ImageRemoveRequest, opts ...grpc.CallOption) (*ImageRemoveResponse, error)
	// Ajoute un tag local à une image
	ImageTag(ctx context.Context, in *ImageTagRequest, opts ...grpc.CallOption) (*ImageTagResponse, error)
	// Importe un rootfs ext4 comme image locale
	ImageImport(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*ImageImportResponse, error)
	// Exporte une image locale vers un fichier ext4
	ImageExport(ctx context.Context, in *ImageExportRequest, opts ...grpc.CallOption) (*ImageExportResponse, error)
	// Liste l'historique metadata d'une image
	ImageHistory(ctx context.Context, in *ImageHistoryRequest, opts ...grpc.CallOption) (*ImageHistoryResponse, error)
	// Supprime les images locales inutilisées
	ImagePrune(ctx context.Context, in *ImagePruneRequest, opts ...grpc.CallOption) (*ImagePruneResponse, error)
	// Phase 1 & 5 : Liste toutes les microVMs
	Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error)
	// Phase 5 : Stream les logs textuels en temps réel
	StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error)
	// Retourne les diagnostics runtime du daemon
	Diagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
}

type fvcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFvcServiceClient(cc grpc.ClientConnInterface) FvcServiceClient {
	return &fvcServiceClient{cc}
}

func (c *fvcServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, FvcService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) RunStream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[0], FvcService_RunStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_RunStreamClient = grpc.ServerStreamingClient[RunEvent]

func (c *fvcServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, FvcService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, FvcService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Rm(ctx context.Context, in *RmRequest, opts ...grpc.CallOption) (*RmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RmResponse)
	err := c.cc.Invoke(ctx, FvcService_Rm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ConsoleInfo(ctx context.Context, in *ConsoleInfoRequest, opts ...grpc.CallOption) (*ConsoleInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleInfoResponse)
	err := c.cc.Invoke(ctx, FvcService_ConsoleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[1], FvcService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_ExecClient = grpc.ServerStreamingClient[ExecEvent]

func (c *fvcServiceClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, FvcService_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, FvcService_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) PullImageStream(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[2], FvcService_PullImageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, OperationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_PullImageStreamClient = grpc.ServerStreamingClient[OperationEvent]

func (c *fvcServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, FvcService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneResponse)
	err := c.cc.Invoke(ctx, FvcService_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, FvcService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, FvcService_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, FvcService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) SnapshotCreate(ctx context.Context, in *SnapshotCreateRequest, opts ...grpc.CallOption) (*SnapshotCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotCreateResponse)
	err := c.cc.Invoke(ctx, FvcService_SnapshotCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, FvcService_SnapshotList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) SnapshotRestore(ctx context.Context, in *SnapshotRestoreRequest, opts ...grpc.CallOption) (*SnapshotRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotRestoreResponse)
	err := c.cc.Invoke(ctx, FvcService_SnapshotRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) SnapshotRemove(ctx context.Context, in *SnapshotRemoveRequest, opts ...grpc.CallOption) (*SnapshotRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotRemoveResponse)
	err := c.cc.Invoke(ctx, FvcService_SnapshotRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*BuildImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildImageResponse)
	err := c.cc.Invoke(ctx, FvcService_BuildImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) BuildImageStream(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[3], FvcService_BuildImageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildImageRequest, OperationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_BuildImageStreamClient = grpc.ServerStreamingClient[OperationEvent]

func (c *fvcServiceClient) ImageInspect(ctx context.Context, in *ImageInspectRequest, opts ...grpc.CallOption) (*ImageInspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageInspectResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageInspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImageRemove(ctx context.Context, in *ImageRemoveRequest, opts ...grpc.CallOption) (*ImageRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageRemoveResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImageTag(ctx context.Context, in *ImageTagRequest, opts ...grpc.CallOption) (*ImageTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageTagResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImageImport(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*ImageImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageImportResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImageExport(ctx context.Context, in *ImageExportRequest, opts ...grpc.CallOption) (*ImageExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageExportResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImageHistory(ctx context.Context, in *ImageHistoryRequest, opts ...grpc.CallOption) (*ImageHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageHistoryResponse)
	err := c.cc.Invoke(ctx, FvcService_ImageHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) ImagePrune(ctx context.Context, in *ImagePruneRequest, opts ...grpc.CallOption) (*ImagePruneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImagePruneResponse)
	err := c.cc.Invoke(ctx, FvcService_ImagePrune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PsResponse)
	err := c.cc.Invoke(ctx, FvcService_Ps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[4], FvcService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_StreamLogsClient = grpc.ServerStreamingClient[LogsResponse]

func (c *fvcServiceClient) Diagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, FvcService_Diagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FvcServiceServer is the server API for FvcService service.
// All implementations must embed UnimplementedFvcServiceServer
// for forward compatibility.
//
// Le service est renommé FvcService (consommé par fvc, implémenter par fvcd)
type FvcServiceServer interface {
	// Phase 1 & 5 : Lance une microVM
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Lance une microVM en streamant les étapes de préparation
	RunStream(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error
	// Phase 5 : Arrête proprement une microVM
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Relance une microVM stoppée
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Supprime une microVM stoppée et ses fichiers locaux
	Rm(context.Context, *RmRequest) (*RmResponse, error)
	// Retourne les chemins locaux nécessaires à la console série
	ConsoleInfo(context.Context, *ConsoleInfoRequest) (*ConsoleInfoResponse, error)
	// Exécute une commande dans une microVM via l'agent invité
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecEvent]) error
	// Retourne les détails complets d'une microVM
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	// Télécharge une image dans le cache local
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	// Télécharge une image en streamant la progression
	PullImageStream(*PullImageRequest, grpc.ServerStreamingServer[OperationEvent]) error
	// Liste les images présentes dans le cache local
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Nettoie les ressources locales inutilisées
	Prune(context.Context, *PruneRequest) (*PruneResponse, error)
	// Retourne les métriques host des microVMs
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Attend qu'une microVM atteigne l'état stopped/down
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	// Force l'arrêt d'une microVM
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	// Crée un snapshot du disque d'une microVM stoppée
	SnapshotCreate(context.Context, *SnapshotCreateRequest) (*SnapshotCreateResponse, error)
	// Liste les snapshots d'une microVM
	SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error)
	// Restaure un snapshot sur le disque d'une microVM stoppée
	SnapshotRestore(context.Context, *SnapshotRestoreRequest) (*SnapshotRestoreResponse, error)
	// Supprime un snapshot
	SnapshotRemove(context.Context, *SnapshotRemoveRequest) (*SnapshotRemoveResponse, error)
	// Construit une image locale depuis un Fvcfile TOML
	BuildImage(context.Context, *BuildImageRequest) (*BuildImageResponse, error)
	// Construit une image locale en streamant les étapes
	BuildImageStream(*BuildImageRequest, grpc.ServerStreamingServer[OperationEvent]) error
	// Inspecte une image locale
	ImageInspect(context.Context, *ImageInspectRequest) (*ImageInspectResponse, error)
	// Supprime une image locale
	ImageRemove(context.Context, *ImageRemoveRequest) (*ImageRemoveResponse, error)
	// Ajoute un tag local à une image
	ImageTag(context.Context, *ImageTagRequest) (*ImageTagResponse, error)
	// Importe un rootfs ext4 comme image locale
	ImageImport(context.Context, *ImageImportRequest) (*ImageImportResponse, error)
	// Exporte une image locale vers un fichier ext4
	ImageExport(context.Context, *ImageExportRequest) (*ImageExportResponse, error)
	// Liste l'historique metadata d'une image
	ImageHistory(context.Context, *ImageHistoryRequest) (*ImageHistoryResponse, error)
	// Supprime les images locales inutilisées
	ImagePrune(context.Context, *ImagePruneRequest) (*ImagePruneResponse, error)
	// Phase 1 & 5 : Liste toutes les microVMs
	Ps(context.Context, *PsRequest) (*PsResponse, error)
	// Phase 5 : Stream les logs textuels en temps réel
	StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error
	// Retourne les diagnostics runtime du daemon
	Diagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
	mustEmbedUnimplementedFvcServiceServer()
}

// UnimplementedFvcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFvcServiceServer struct{}

func (UnimplementedFvcServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedFvcServiceServer) RunStream(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method RunStream not implemented")
}
func (UnimplementedFvcServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedFvcServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedFvcServiceServer) Rm(context.Context, *RmRequest) (*RmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rm not implemented")
}
func (UnimplementedFvcServiceServer) ConsoleInfo(context.Context, *ConsoleInfoRequest) (*ConsoleInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsoleInfo not implemented")
}
func (UnimplementedFvcServiceServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecEvent]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedFvcServiceServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedFvcServiceServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedFvcServiceServer) PullImageStream(*PullImageRequest, grpc.ServerStreamingServer[OperationEvent]) error {
	return status.Error(codes.Unimplemented, "method PullImageStream not implemented")
}
func (UnimplementedFvcServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedFvcServiceServer) Prune(context.Context, *PruneRequest) (*PruneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedFvcServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedFvcServiceServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedFvcServiceServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedFvcServiceServer) SnapshotCreate(context.Context, *SnapshotCreateRequest) (*SnapshotCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotCreate not implemented")
}
func (UnimplementedFvcServiceServer) SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotList not implemented")
}
func (UnimplementedFvcServiceServer) SnapshotRestore(context.Context, *SnapshotRestoreRequest) (*SnapshotRestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotRestore not implemented")
}
func (UnimplementedFvcServiceServer) SnapshotRemove(context.Context, *SnapshotRemoveRequest) (*SnapshotRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotRemove not implemented")
}
func (UnimplementedFvcServiceServer) BuildImage(context.Context, *BuildImageRequest) (*BuildImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildImage not implemented")
}
func (UnimplementedFvcServiceServer) BuildImageStream(*BuildImageRequest, grpc.ServerStreamingServer[OperationEvent]) error {
	return status.Error(codes.Unimplemented, "method BuildImageStream not implemented")
}
func (UnimplementedFvcServiceServer) ImageInspect(context.Context, *ImageInspectRequest) (*ImageInspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageInspect not implemented")
}
func (UnimplementedFvcServiceServer) ImageRemove(context.Context, *ImageRemoveRequest) (*ImageRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageRemove not implemented")
}
func (UnimplementedFvcServiceServer) ImageTag(context.Context, *ImageTagRequest) (*ImageTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageTag not implemented")
}
func (UnimplementedFvcServiceServer) ImageImport(context.Context, *ImageImportRequest) (*ImageImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageImport not implemented")
}
func (UnimplementedFvcServiceServer) ImageExport(context.Context, *ImageExportRequest) (*ImageExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageExport not implemented")
}
func (UnimplementedFvcServiceServer) ImageHistory(context.Context, *ImageHistoryRequest) (*ImageHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageHistory not implemented")
}
func (UnimplementedFvcServiceServer) ImagePrune(context.Context, *ImagePruneRequest) (*ImagePruneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImagePrune not implemented")
}
func (UnimplementedFvcServiceServer) Ps(context.Context, *PsRequest) (*PsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ps not implemented")
}
func (UnimplementedFvcServiceServer) StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedFvcServiceServer) Diagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diagnostics not implemented")
}
func (UnimplementedFvcServiceServer) mustEmbedUnimplementedFvcServiceServer() {}
func (UnimplementedFvcServiceServer) testEmbeddedByValue()                    {}

// UnsafeFvcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FvcServiceServer will
// result in compilation errors.
type UnsafeFvcServiceServer interface {
	mustEmbedUnimplementedFvcServiceServer()
}

func RegisterFvcServiceServer(s grpc.ServiceRegistrar, srv FvcServiceServer) {
	// If the following call panics, it indicates UnimplementedFvcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FvcService_ServiceDesc, srv)
}

func _FvcService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_RunStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).RunStream(m, &grpc.GenericServerStream[RunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_RunStreamServer = grpc.ServerStreamingServer[RunEvent]

func _FvcService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Rm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Rm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Rm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Rm(ctx, req.(*RmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ConsoleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ConsoleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ConsoleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ConsoleInfo(ctx, req.(*ConsoleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_ExecServer = grpc.ServerStreamingServer[ExecEvent]

func _FvcService_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_PullImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).PullImageStream(m, &grpc.GenericServerStream[PullImageRequest, OperationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_PullImageStreamServer = grpc.ServerStreamingServer[OperationEvent]

func _FvcService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_SnapshotCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).SnapshotCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_SnapshotCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).SnapshotCreate(ctx, req.(*SnapshotCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_SnapshotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).SnapshotList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_SnapshotList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).SnapshotList(ctx, req.(*SnapshotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_SnapshotRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).SnapshotRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_SnapshotRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).SnapshotRestore(ctx, req.(*SnapshotRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_SnapshotRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).SnapshotRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_SnapshotRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).SnapshotRemove(ctx, req.(*SnapshotRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_BuildImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).BuildImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_BuildImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).BuildImage(ctx, req.(*BuildImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_BuildImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).BuildImageStream(m, &grpc.GenericServerStream[BuildImageRequest, OperationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_BuildImageStreamServer = grpc.ServerStreamingServer[OperationEvent]

func _FvcService_ImageInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageInspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageInspect(ctx, req.(*ImageInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImageRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageRemove(ctx, req.(*ImageRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImageTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageTag(ctx, req.(*ImageTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImageImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageImport(ctx, req.(*ImageImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImageExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageExport(ctx, req.(*ImageExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImageHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImageHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImageHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImageHistory(ctx, req.(*ImageHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_ImagePrune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagePruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).ImagePrune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_ImagePrune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).ImagePrune(ctx, req.(*ImagePruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Ps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Ps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Ps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Ps(ctx, req.(*PsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).StreamLogs(m, &grpc.GenericServerStream[LogsRequest, LogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_StreamLogsServer = grpc.ServerStreamingServer[LogsResponse]

func _FvcService_Diagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Diagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Diagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Diagnostics(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FvcService_ServiceDesc is the grpc.ServiceDesc for FvcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FvcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fvc.FvcService",
	HandlerType: (*FvcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _FvcService_Run_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _FvcService_Stop_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _FvcService_Start_Handler,
		},
		{
			MethodName: "Rm",
			Handler:    _FvcService_Rm_Handler,
		},
		{
			MethodName: "ConsoleInfo",
			Handler:    _FvcService_ConsoleInfo_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _FvcService_Inspect_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _FvcService_PullImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _FvcService_ListImages_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _FvcService_Prune_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _FvcService_Stats_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _FvcService_Wait_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _FvcService_Kill_Handler,
		},
		{
			MethodName: "SnapshotCreate",
			Handler:    _FvcService_SnapshotCreate_Handler,
		},
		{
			MethodName: "SnapshotList",
			Handler:    _FvcService_SnapshotList_Handler,
		},
		{
			MethodName: "SnapshotRestore",
			Handler:    _FvcService_SnapshotRestore_Handler,
		},
		{
			MethodName: "SnapshotRemove",
			Handler:    _FvcService_SnapshotRemove_Handler,
		},
		{
			MethodName: "BuildImage",
			Handler:    _FvcService_BuildImage_Handler,
		},
		{
			MethodName: "ImageInspect",
			Handler:    _FvcService_ImageInspect_Handler,
		},
		{
			MethodName: "ImageRemove",
			Handler:    _FvcService_ImageRemove_Handler,
		},
		{
			MethodName: "ImageTag",
			Handler:    _FvcService_ImageTag_Handler,
		},
		{
			MethodName: "ImageImport",
			Handler:    _FvcService_ImageImport_Handler,
		},
		{
			MethodName: "ImageExport",
			Handler:    _FvcService_ImageExport_Handler,
		},
		{
			MethodName: "ImageHistory",
			Handler:    _FvcService_ImageHistory_Handler,
		},
		{
			MethodName: "ImagePrune",
			Handler:    _FvcService_ImagePrune_Handler,
		},
		{
			MethodName: "Ps",
			Handler:    _FvcService_Ps_Handler,
		},
		{
			MethodName: "Diagnostics",
			Handler:    _FvcService_Diagnostics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunStream",
			Handler:       _FvcService_RunStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _FvcService_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullImageStream",
			Handler:       _FvcService_PullImageStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildImageStream",
			Handler:       _FvcService_BuildImageStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _FvcService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/fvc.proto",
}
