// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/fvc.proto

// Le package correspond maintenant au nom de ton projet : fvc

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FvcService_Run_FullMethodName        = "/fvc.FvcService/Run"
	FvcService_Stop_FullMethodName       = "/fvc.FvcService/Stop"
	FvcService_Ps_FullMethodName         = "/fvc.FvcService/Ps"
	FvcService_StreamLogs_FullMethodName = "/fvc.FvcService/StreamLogs"
)

// FvcServiceClient is the client API for FvcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Le service est renommé FvcService (consommé par fvc, implémenter par fvcd)
type FvcServiceClient interface {
	// Phase 1 & 5 : Lance une microVM
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Phase 5 : Arrête proprement une microVM
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Phase 1 & 5 : Liste toutes les microVMs
	Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error)
	// Phase 5 : Stream les logs textuels en temps réel
	StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error)
}

type fvcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFvcServiceClient(cc grpc.ClientConnInterface) FvcServiceClient {
	return &fvcServiceClient{cc}
}

func (c *fvcServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, FvcService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, FvcService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PsResponse)
	err := c.cc.Invoke(ctx, FvcService_Ps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvcServiceClient) StreamLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FvcService_ServiceDesc.Streams[0], FvcService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_StreamLogsClient = grpc.ServerStreamingClient[LogsResponse]

// FvcServiceServer is the server API for FvcService service.
// All implementations must embed UnimplementedFvcServiceServer
// for forward compatibility.
//
// Le service est renommé FvcService (consommé par fvc, implémenter par fvcd)
type FvcServiceServer interface {
	// Phase 1 & 5 : Lance une microVM
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Phase 5 : Arrête proprement une microVM
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Phase 1 & 5 : Liste toutes les microVMs
	Ps(context.Context, *PsRequest) (*PsResponse, error)
	// Phase 5 : Stream les logs textuels en temps réel
	StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error
	mustEmbedUnimplementedFvcServiceServer()
}

// UnimplementedFvcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFvcServiceServer struct{}

func (UnimplementedFvcServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedFvcServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedFvcServiceServer) Ps(context.Context, *PsRequest) (*PsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ps not implemented")
}
func (UnimplementedFvcServiceServer) StreamLogs(*LogsRequest, grpc.ServerStreamingServer[LogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedFvcServiceServer) mustEmbedUnimplementedFvcServiceServer() {}
func (UnimplementedFvcServiceServer) testEmbeddedByValue()                    {}

// UnsafeFvcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FvcServiceServer will
// result in compilation errors.
type UnsafeFvcServiceServer interface {
	mustEmbedUnimplementedFvcServiceServer()
}

func RegisterFvcServiceServer(s grpc.ServiceRegistrar, srv FvcServiceServer) {
	// If the following call panics, it indicates UnimplementedFvcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FvcService_ServiceDesc, srv)
}

func _FvcService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_Ps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FvcServiceServer).Ps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FvcService_Ps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FvcServiceServer).Ps(ctx, req.(*PsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FvcService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FvcServiceServer).StreamLogs(m, &grpc.GenericServerStream[LogsRequest, LogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FvcService_StreamLogsServer = grpc.ServerStreamingServer[LogsResponse]

// FvcService_ServiceDesc is the grpc.ServiceDesc for FvcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FvcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fvc.FvcService",
	HandlerType: (*FvcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _FvcService_Run_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _FvcService_Stop_Handler,
		},
		{
			MethodName: "Ps",
			Handler:    _FvcService_Ps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _FvcService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/fvc.proto",
}
